/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Member, NewsPost, User, Comment } from './types';
import { NORTH_MEMBERS } from './north_members';
import { SOUTH_MEMBERS } from './south_members';

export const BRANCHES = [
  'Văn phòng Công ty MFS',
  'Chi nhánh miền Bắc',
  'Chi nhánh miền Trung',
  'Chi nhánh miền Nam'
];

export const DEPARTMENTS = [
  'BAN TỔNG GIÁM ĐỐC',
  'P. TỔ CHỨC - HÀNH CHÍNH',
  'P. TÀI CHÍNH - KẾ TOÁN',
  'P. HẠ TẦNG - VIỄN THÔNG',
  'P. KẾ HOẠCH - KINH DOANH',
  'P. CÔNG NGHỆ SỐ',
  'Phòng KD & VHDV',
  'Phòng HCTH',
  'Phòng VH HT-VT'
];

export const BRANCH_DEPARTMENTS: Record<string, string[]> = {
  'Văn phòng Công ty MFS': [
    'BAN TỔNG GIÁM ĐỐC',
    'P. TỔ CHỨC - HÀNH CHÍNH',
    'P. TÀI CHÍNH - KẾ TOÁN',
    'P. HẠ TẦNG - VIỄN THÔNG',
    'P. KẾ HOẠCH - KINH DOANH',
    'P. CÔNG NGHỆ SỐ'
  ],
  'Chi nhánh miền Bắc': [
    'Phòng KD & VHDV',
    'Phòng HCTH',
    'Phòng VH HT-VT'
  ],
  'Chi nhánh miền Trung': [
    'Phòng KD & VHDV',
    'Phòng HCTH',
    'Phòng VH HT-VT'
  ],
  'Chi nhánh miền Nam': [
    'Phòng KD & VHDV',
    'Phòng HCTH',
    'Phòng VH HT-VT'
  ]
};

export function migrateBranchAndDept(rawBranch: string, rawDept: string): { branch: string, department: string } {
  const b = rawBranch ? rawBranch.trim() : '';
  const d = rawDept ? rawDept.trim() : '';

  // 1. Map Branch
  let finalBranch = 'Văn phòng Công ty MFS';
  const cleanB = b.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/đ/g, "d");
  const cleanD = d.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/đ/g, "d");

  if (b === 'Chi nhánh miền Bắc' || cleanB === 'chi nhanh mien bac' || b === 'MFS Chi nhánh Miền Bắc') {
    finalBranch = 'Chi nhánh miền Bắc';
  } else if (b === 'Chi nhánh miền Trung' || cleanB === 'chi nhanh mien trung' || b === 'MFS Chi nhánh Miền Trung') {
    finalBranch = 'Chi nhánh miền Trung';
  } else if (b === 'Chi nhánh miền Nam' || cleanB === 'chi nhanh mien nam' || b === 'MFS Chi nhánh Miền Nam') {
    finalBranch = 'Chi nhánh miền Nam';
  } else if (cleanB.includes('van phong') || cleanB.includes('tong cong ty') || cleanB.includes('vp tct') || cleanB.includes('vptct') || cleanB.includes('van phong tct') || cleanB === 'mfs') {
    finalBranch = 'Văn phòng Công ty MFS';
  } else if (cleanB.includes('ha noi') || cleanB.includes('mien bac') || cleanB.includes('bac') || cleanB.includes('hn')) {
    // Determine based on Department if it belongs to General Headquarters or Northern Branch
    if (cleanD.includes('giam doc') || cleanD.includes('tgd') || cleanD.includes('bgd') ||
        cleanD.includes('cong nghe so') || cleanD.includes('cns') || 
        cleanD.includes('to chuc') || cleanD.includes('hanh chinh') || cleanD.includes('tchc') || 
        cleanD.includes('ke toan') || cleanD.includes('tai chinh') ||
        cleanD.includes('ha tang') || cleanD.includes('vien thong') ||
        cleanD.includes('ke hoach') || cleanD.includes('kinh doanh') || cleanD.includes('kh kd') || cleanD.includes('khkd') || cleanD.includes('kinh doanh tong hop') || cleanD.includes('kdth')) {
      finalBranch = 'Văn phòng Công ty MFS';
    } else {
      finalBranch = 'Chi nhánh miền Bắc';
    }
  } else if (cleanB.includes('mien trung') || cleanB.includes('trung') || cleanB.includes('da nang') || cleanB.includes('binh dinh') || cleanB.includes('khanh hoa')) {
    finalBranch = 'Chi nhánh miền Trung';
  } else if (cleanB.includes('mien nam') || cleanB.includes('nam') || cleanB.includes('ho chi minh') || cleanB.includes('sai gon') || cleanB.includes('hcm') || cleanB.includes('mien tay') || cleanB.includes('can tho') || cleanB.includes('tay')) {
    finalBranch = 'Chi nhánh miền Nam';
  } else {
    // Look at department fallback if branch is unknown
    if (cleanD.includes('giam doc') || cleanD.includes('tgd') || cleanD.includes('bgd') ||
        cleanD.includes('cong nghe so') || cleanD.includes('cns') || 
        cleanD.includes('to chuc') || cleanD.includes('hanh chinh') || cleanD.includes('tchc') || 
        cleanD.includes('ke toan') || cleanD.includes('tai chinh') ||
        cleanD.includes('ha tang') || cleanD.includes('vien thong') ||
        cleanD.includes('ke hoach') || cleanD.includes('kinh doanh') || cleanD.includes('kh kd') || cleanD.includes('khkd')) {
      finalBranch = 'Văn phòng Công ty MFS';
    } else {
      finalBranch = 'Chi nhánh miền Bắc';
    }
  }

  // 2. Map Department based on Branch
  let finalDept = '';
  if (finalBranch === 'Văn phòng Công ty MFS') {
    if (cleanD.includes('giam doc') || cleanD.includes('tgd') || cleanD.includes('bgd')) {
      finalDept = 'BAN TỔNG GIÁM ĐỐC';
    } else if (cleanD.includes('to chuc') || cleanD.includes('tchc') || cleanD.includes('hanh chinh') || cleanD.includes('tuyển dung') || cleanD.includes('bhxh') || cleanD.includes('luong')) {
      finalDept = 'P. TỔ CHỨC - HÀNH CHÍNH';
    } else if (cleanD.includes('ke toan') || cleanD.includes('tai chinh') || cleanD.includes('ngan hang') || cleanD.includes('thue') || cleanD.includes('quy')) {
      finalDept = 'P. TÀI CHÍNH - KẾ TOÁN';
    } else if (cleanD.includes('ha tang') || cleanD.includes('vien thong') || cleanD.includes('ky thuat') || cleanD.includes('mang luoi')) {
      finalDept = 'P. HẠ TẦNG - VIỄN THÔNG';
    } else if (cleanD.includes('ke hoach') || cleanD.includes('kinh doanh') || cleanD.includes('kh kd') || cleanD.includes('khkd') || cleanD.includes('kdth')) {
      finalDept = 'P. KẾ HOẠCH - KINH DOANH';
    } else if (cleanD.includes('cong nghe so') || cleanD.includes('cns') || cleanD.includes('digital') || cleanD.includes('it') || cleanD.includes('phan mem')) {
      finalDept = 'P. CÔNG NGHỆ SỐ';
    } else {
      finalDept = 'P. KẾ HOẠCH - KINH DOANH'; // Default fallback for HQ
    }
  } else {
    // Branches have: 'Phòng KD & VHDV', 'Phòng HCTH', 'Phòng VH HT-VT'
    if (cleanD.includes('kinh doanh') || cleanD.includes('cskh') || cleanD.includes('cham soc') || cleanD.includes('inbound') || cleanD.includes('callout') || cleanD.includes('dich vu') || cleanD.includes('vhdv') || cleanD.includes('kd')) {
      finalDept = 'Phòng KD & VHDV';
    } else if (cleanD.includes('hanh chinh') || cleanD.includes('hcth') || cleanD.includes('tong hop') || cleanD.includes('van phong')) {
      finalDept = 'Phòng HCTH';
    } else if (cleanD.includes('ky thuat') || cleanD.includes('ha tang') || cleanD.includes('van hanh') || cleanD.includes('vh') || cleanD.includes('htvt') || cleanD.includes('uctt') || cleanD.includes('truyen dan') || cleanD.includes('noc')) {
      finalDept = 'Phòng VH HT-VT';
    } else {
      finalDept = 'Phòng KD & VHDV'; // Default fallback for branch
    }
  }

  return { branch: finalBranch, department: finalDept };
}

export const DEPARTMENT_MAP: Record<string, string> = {
  // Legacy / Old departments mapping to preserve historical data
  'Phòng TCHC': 'P. TỔ CHỨC - HÀNH CHÍNH',
  'Phòng Kế toán': 'P. TÀI CHÍNH - KẾ TOÁN',
  'Phòng CNS': 'P. CÔNG NGHỆ SỐ',
  'Phòng KH KD': 'P. KẾ HOẠCH - KINH DOANH',
  'TCHC': 'P. TỔ CHỨC - HÀNH CHÍNH',
  'KE TOAN': 'P. TÀI CHÍNH - KẾ TOÁN',
  'CNS': 'P. CÔNG NGHỆ SỐ',
  'KH KD': 'P. KẾ HOẠCH - KINH DOANH',
  
  // New departments mapping
  'BAN TỔNG GIÁM ĐỐC': 'BAN TỔNG GIÁM ĐỐC',
  'BAN TONG GIAM DOC': 'BAN TỔNG GIÁM ĐỐC',
  'P. TỔ CHỨC - HÀNH CHÍNH': 'P. TỔ CHỨC - HÀNH CHÍNH',
  'P. TO CHUC - HANH CHINH': 'P. TỔ CHỨC - HÀNH CHÍNH',
  'P. TÀI CHÍNH - KẾ TOÁN': 'P. TÀI CHÍNH - KẾ TOÁN',
  'P. TAI CHINH - KE TOAN': 'P. TÀI CHÍNH - KẾ TOÁN',
  'P. HẠ TẦNG - VIỄN THÔNG': 'P. HẠ TẦNG - VIỄN THÔNG',
  'P. HA TANG - VIEN THONG': 'P. HẠ TẦNG - VIỄN THÔNG',
  'P. KẾ HOẠCH - KINH DOANH': 'P. KẾ HOẠCH - KINH DOANH',
  'P. KE HOACH - KINH DOANH': 'P. KẾ HOẠCH - KINH DOANH',
  'P. CÔNG NGHỆ SỐ': 'P. CÔNG NGHỆ SỐ',
  'P. CONG NGHE SO': 'P. CÔNG NGHỆ SỐ',
  
  'Phòng KD & VHDV': 'Phòng KD & VHDV',
  'KD & VHDV': 'Phòng KD & VHDV',
  'Phòng HCTH': 'Phòng HCTH',
  'HCTH': 'Phòng HCTH',
  'Phòng VH HT-VT': 'Phòng VH HT-VT',
  'VH HT-VT': 'Phòng VH HT-VT'
};

export const UNION_POSITIONS = [
  'Đoàn viên',
  'Bí thư Chi đoàn',
  'Phó Bí thư Chi đoàn',
  'Ủy viên Ban Chấp hành công đoàn'
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user_1',
    email: 'huongns@mobifoneservice.com.vn',
    fullName: 'Nguyễn Sông Hương',
    role: 'ADMIN_SUPER',
    branch: 'All',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    employeeCode: 'MFS00382'
  },
  {
    id: 'user_2',
    email: 'hungnv@mobifoneservice.com.vn',
    fullName: 'Nguyễn Văn Hùng',
    role: 'ADMIN_BRANCH',
    branch: 'Chi nhánh miền Bắc',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150',
    employeeCode: 'UC00586'
  },
  {
    id: 'user_3',
    email: 'phuoctth@mobifoneservice.com.vn',
    fullName: 'Tô Thị Hồng Phước',
    role: 'ADMIN_BRANCH',
    branch: 'Chi nhánh miền Nam',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    employeeCode: 'MFS00125'
  },
  {
    id: 'user_4',
    email: 'lamtt@mobifoneservice.com.vn',
    fullName: 'Trần Tiến Lâm',
    role: 'MEMBER',
    branch: 'Chi nhánh miền Bắc',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    employeeCode: 'MFS00296'
  },
  {
    id: 'user_5',
    email: 'nguyenhoangvy182@gmail.com',
    fullName: 'Nguyễn Hoàng Vy',
    role: 'MEMBER',
    branch: 'Chi nhánh miền Nam',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    employeeCode: 'DTV02806'
  }
];

export const INITIAL_MEMBERS: Member[] = [
  ...NORTH_MEMBERS,
  ...SOUTH_MEMBERS,
  {
    "MemberID": "mem_mfs_1",
    "EmployeeCode": "MFS00001",
    "FullName": "Vũ Quang Hải",
    "Gender": "Nam",
    "DOB": "1973-02-19",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "BAN TỔNG GIÁM ĐỐC",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0903426688",
    "Email": "haivq@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Tổng Giám đốc"
  },
  {
    "MemberID": "mem_mfs_2",
    "EmployeeCode": "MFS00356",
    "FullName": "Nguyễn Ngọc Thảo",
    "Gender": "Nam",
    "DOB": "1984-07-10",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "BAN TỔNG GIÁM ĐỐC",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0936916668",
    "Email": "thaonn@mobifoneservice.com.vn",
    "UnionPosition": "Chủ tịch Công đoàn Công ty",
    "Title": "Phó Tổng Giám đốc"
  },
  {
    "MemberID": "mem_mfs_3",
    "EmployeeCode": "MFS00075",
    "FullName": "Tăng Ngọc Sơn",
    "Gender": "Nam",
    "DOB": "1980-12-22",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0939595697",
    "Email": "sontn@mobifoneservice.com.vn",
    "UnionPosition": "UV BCH Công đoàn Công ty",
    "Title": "Trưởng phòng TCHC"
  },
  {
    "MemberID": "mem_mfs_4",
    "EmployeeCode": "MFS00077",
    "FullName": "Nguyễn Thu Huyền",
    "Gender": "Nữ",
    "DOB": "1980-01-14",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0906140180",
    "Email": "huyennt@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Trưởng phòng HCTH"
  },
  {
    "MemberID": "mem_mfs_5",
    "EmployeeCode": "MFS00312",
    "FullName": "Bùi Thị Yêu",
    "Gender": "Nữ",
    "DOB": "1991-02-20",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0979601791",
    "Email": "yeubt@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Tuyển dụng - BHXH"
  },
  {
    "MemberID": "mem_mfs_6",
    "EmployeeCode": "MFS00027",
    "FullName": "Phạm Thị Thu Nga",
    "Gender": "Nữ",
    "DOB": "1991-07-01",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0986156088",
    "Email": "ngaptt@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên lao động - tiền lương NVTV"
  },
  {
    "MemberID": "mem_mfs_7",
    "EmployeeCode": "MFS00269",
    "FullName": "Phạm Thị Bích Phương",
    "Gender": "Nữ",
    "DOB": "1990-10-28",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0942281090",
    "Email": "phuongptb@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên lao động - tiền lương HTNV"
  },
  {
    "MemberID": "mem_mfs_8",
    "EmployeeCode": "MFS00030",
    "FullName": "Nguyễn Thái Ngân",
    "Gender": "Nữ",
    "DOB": "1992-09-08",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0903278188",
    "Email": "ngannt@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên thư ký HĐQT"
  },
  {
    "MemberID": "mem_mfs_9",
    "EmployeeCode": "MFS00172",
    "FullName": "Lê Thị Thu Hằng",
    "Gender": "Nữ",
    "DOB": "1985-10-29",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0938660000",
    "Email": "hangltt@mobifoneservice.com.vn",
    "UnionPosition": "UV BCH Công đoàn Công ty",
    "Title": "Chuyên viên phụ trách công đoàn"
  },
  {
    "MemberID": "mem_mfs_10",
    "EmployeeCode": "MFS00005",
    "FullName": "Đỗ Thị Hiên",
    "Gender": "Nữ",
    "DOB": "1978-12-18",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0936220000",
    "Email": "hienvp@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Hành chính"
  },
  {
    "MemberID": "mem_mfs_11",
    "EmployeeCode": "MFS00012",
    "FullName": "Nguyễn Huyền Trang",
    "Gender": "Nữ",
    "DOB": "1990-11-14",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0932203204",
    "Email": "trangnh@mobifoneservice.com.vn",
    "UnionPosition": "Tổ PhóTổ Công đoàn Khối Hỗ trợ",
    "Title": "Nhân viên Lễ tân"
  },
  {
    "MemberID": "mem_mfs_12",
    "EmployeeCode": "MFS00381",
    "FullName": "Đinh Văn Đức",
    "Gender": "Nam",
    "DOB": "1977-09-02",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. TỔ CHỨC - HÀNH CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0902091977",
    "Email": "ducdv@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên Lái xe"
  },
  {
    "MemberID": "mem_mfs_13",
    "EmployeeCode": "MFS00017",
    "FullName": "Nguyễn Anh Tú",
    "Gender": "Nam",
    "DOB": "1977-10-10",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0906273356",
    "Email": "tuna@mobifoneservice.com.vn",
    "UnionPosition": "Phó Chủ tịch Công đoàn Công ty",
    "Title": "Kế toán trưởng"
  },
  {
    "MemberID": "mem_mfs_14",
    "EmployeeCode": "MFS00020",
    "FullName": "Đỗ Thị Thanh Thủy",
    "Gender": "Nữ",
    "DOB": "1987-10-07",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0988459887",
    "Email": "thuydtt@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kế toán tổng hợp"
  },
  {
    "MemberID": "mem_mfs_15",
    "EmployeeCode": "MFS00024",
    "FullName": "Trần Thị Hồng Nhung",
    "Gender": "Nữ",
    "DOB": "1990-10-08",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0948240454",
    "Email": "nhungtth@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kế toán DT-CP"
  },
  {
    "MemberID": "mem_mfs_16",
    "EmployeeCode": "MFS00275",
    "FullName": "Nguyễn Thị Thu Huyền",
    "Gender": "Nữ",
    "DOB": "1987-06-11",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0989110687",
    "Email": "huyenntt@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên kế toán thuế"
  },
  {
    "MemberID": "mem_mfs_17",
    "EmployeeCode": "MFS00022",
    "FullName": "Vũ Thị Huyền Trang",
    "Gender": "Nữ",
    "DOB": "1987-11-04",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0934088566",
    "Email": "trangvth@mobifoneservice.com.vn",
    "UnionPosition": "UVBCH CĐV VP Tổ trưởng Tổ Công đoàn Khối Hỗ trợ",
    "Title": "Chuyên viên Kế toán thanh toán, Thủ kho - Thủ quỹ"
  },
  {
    "MemberID": "mem_mfs_18",
    "EmployeeCode": "MFS00267",
    "FullName": "Vũ Minh Nguyệt",
    "Gender": "Nữ",
    "DOB": "1988-10-02",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0977511880",
    "Email": "nguyetvm@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kế toán ngân hàng"
  },
  {
    "MemberID": "mem_mfs_19",
    "EmployeeCode": "MFS00181",
    "FullName": "Phan Thị Thu Hiền",
    "Gender": "Nữ",
    "DOB": "1994-10-25",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0384695674",
    "Email": "hienptt@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kế toán thanh toán"
  },
  {
    "MemberID": "mem_mfs_20",
    "EmployeeCode": "MFS00274",
    "FullName": "Lê Thanh Nga",
    "Gender": "Nữ",
    "DOB": "1979-07-14",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0936856789",
    "Email": "ngalt1@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kế toán thanh toán"
  },
  {
    "MemberID": "mem_mfs_21",
    "EmployeeCode": "MFS00352",
    "FullName": "Phạm Thị Thu Hiền",
    "Gender": "Nữ",
    "DOB": "1991-06-24",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0931301179",
    "Email": "hienptt1@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kế toán"
  },
  {
    "MemberID": "mem_mfs_22",
    "EmployeeCode": "MFS00228",
    "FullName": "Nguyễn Thị Thu Nga",
    "Gender": "Nữ",
    "DOB": "1975-10-15",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ TOÁN - TÀI CHÍNH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0982104875",
    "Email": "ngantt@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kế toán DV VMB"
  },
  {
    "MemberID": "mem_mfs_23",
    "EmployeeCode": "MFS00004",
    "FullName": "Nguyễn Xuân Lộc",
    "Gender": "Nam",
    "DOB": "1987-10-10",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0939595693",
    "Email": "locnx@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Trưởng phòng KHKD"
  },
  {
    "MemberID": "mem_mfs_24",
    "EmployeeCode": "MFS00369",
    "FullName": "Nguyễn Thái Hưng",
    "Gender": "Nam",
    "DOB": "1972-03-02",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0903218453",
    "Email": "hungnt@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Phó phòng KHKD"
  },
  {
    "MemberID": "mem_mfs_25",
    "EmployeeCode": "MFS00078",
    "FullName": "Luyện Diệu Linh",
    "Gender": "Nữ",
    "DOB": "1984-11-23",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0904885152",
    "Email": "linhld@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên quản lý điều hành và phát triển DV CallCenter"
  },
  {
    "MemberID": "mem_mfs_26",
    "EmployeeCode": "MFS00094",
    "FullName": "Nguyễn Đặng Hạ Thy",
    "Gender": "Nữ",
    "DOB": "1982-05-14",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0902587557",
    "Email": "thyndh@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên quản lý điều hành và phát triển DV CallCenter"
  },
  {
    "MemberID": "mem_mfs_27",
    "EmployeeCode": "MFS00298",
    "FullName": "Nguyễn Thị Thanh Mai",
    "Gender": "Nữ",
    "DOB": "1995-10-22",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0768566588",
    "Email": "maintt1@mobifoneservice.com.vn",
    "UnionPosition": "Tổ  PhóTổ Công đoàn Khối KD",
    "Title": "Chuyên viên quản lý điều hành và phát triển DV CallCenter"
  },
  {
    "MemberID": "mem_mfs_28",
    "EmployeeCode": "MFS00308",
    "FullName": "Cái Thị Phương Anh",
    "Gender": "Nữ",
    "DOB": "1982-09-04",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0903484894",
    "Email": "anhctp@mobifoneservice.com.vn",
    "UnionPosition": "UVBCH Công đoàn Công ty",
    "Title": "Chuyên viên quản lý điều hành và phát triển DV CSKH khác"
  },
  {
    "MemberID": "mem_mfs_29",
    "EmployeeCode": "MFS00215",
    "FullName": "Nguyễn Thị Diệu Linh",
    "Gender": "Nữ",
    "DOB": "1993-10-14",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0903453686",
    "Email": "linhntd@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên quản lý điều hành và phát triển DV CSKH khác"
  },
  {
    "MemberID": "mem_mfs_30",
    "EmployeeCode": "MFS00031",
    "FullName": "Vũ Văn Trọng",
    "Gender": "Nam",
    "DOB": "1990-06-06",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0937092555",
    "Email": "trongvv@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên quản lý điều hành và phát triển DV HTNV"
  },
  {
    "MemberID": "mem_mfs_31",
    "EmployeeCode": "MFS00163",
    "FullName": "Hà Thị Nhàn",
    "Gender": "Nữ",
    "DOB": "1992-04-15",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0903417456",
    "Email": "nhanht@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kinh doanh DV SMS Brandname, IPCC-ASUS"
  },
  {
    "MemberID": "mem_mfs_32",
    "EmployeeCode": "MFS00251",
    "FullName": "Trần Thị Vi",
    "Gender": "Nữ",
    "DOB": "1985-10-16",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0904578682",
    "Email": "vith@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kinh doanh DV Bán vé máy bay"
  },
  {
    "MemberID": "mem_mfs_33",
    "EmployeeCode": "MFS00006",
    "FullName": "Nguyễn Danh Kha",
    "Gender": "Nam",
    "DOB": "1970-05-05",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0939595698",
    "Email": "khand@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên Kinh doanh DV Bán vé máy bay; SPDV CNTT"
  },
  {
    "MemberID": "mem_mfs_34",
    "EmployeeCode": "MFS00382",
    "FullName": "Nguyễn Sông Hương",
    "Gender": "Nam",
    "DOB": "1979-11-01",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. CÔNG NGHỆ SỐ",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0979118820",
    "Email": "huongns@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Trưởng phòng CNS"
  },
  {
    "MemberID": "mem_mfs_35",
    "EmployeeCode": "MFS00039",
    "FullName": "Nguyễn Thanh Bình",
    "Gender": "Nam",
    "DOB": "1982-02-27",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. CÔNG NGHỆ SỐ",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0902278000",
    "Email": "binhnt1@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Phó phòng CNS"
  },
  {
    "MemberID": "mem_mfs_36",
    "EmployeeCode": "MFS00074",
    "FullName": "Cao Thị Thủy Lan",
    "Gender": "Nữ",
    "DOB": "1993-11-03",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. CÔNG NGHỆ SỐ",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0934640686",
    "Email": "lanctt@mobifoneservice.com.vn",
    "UnionPosition": "Tổ trưởng Tổ Công đoàn Khối KD",
    "Title": "Chuyên viên đối soát thanh toán"
  },
  {
    "MemberID": "mem_mfs_37",
    "EmployeeCode": "MFS00375",
    "FullName": "Nguyễn Quang Huy",
    "Gender": "Nam",
    "DOB": "1993-01-15",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0961561330",
    "Email": "huynq@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên quản lý điều hành và phát triển DV CSKH"
  },
  {
    "MemberID": "mem_mfs_38",
    "EmployeeCode": "MFS00079",
    "FullName": "Lê Đình Hưng",
    "Gender": "Nam",
    "DOB": "1979-01-22",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. KẾ HOẠCH - KINH DOANH",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0902090299",
    "Email": "hungld@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên quản lý điều hành và phát triển DV CSKH"
  },
  {
    "MemberID": "mem_mfs_39",
    "EmployeeCode": "MFS00073",
    "FullName": "Vũ Quang Trung",
    "Gender": "Nam",
    "DOB": "1991-07-06",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. CÔNG NGHỆ SỐ",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0934228666",
    "Email": "trungvq@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên quản lý điều hành DV GTGT và phát triển DV giải pháp CNTT mới"
  },
  {
    "MemberID": "mem_mfs_40",
    "EmployeeCode": "MFS00299",
    "FullName": "Tưởng Huy Linh",
    "Gender": "Nam",
    "DOB": "1984-07-08",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. HẠ TẦNG - VIỄN THÔNG",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0933186966",
    "Email": "linhth@mobifoneservice.com.vn",
    "UnionPosition": "UVBCH, Chủ nhiệm UBKT Công đoàn Công ty",
    "Title": "Phó phòng HTVT"
  },
  {
    "MemberID": "mem_mfs_41",
    "EmployeeCode": "MFS00046",
    "FullName": "Đặng Việt Hưng",
    "Gender": "Nam",
    "DOB": "1980-06-30",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. HẠ TẦNG - VIỄN THÔNG",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0904880002",
    "Email": "hungdv@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Phó phòng HTVT"
  },
  {
    "MemberID": "mem_mfs_42",
    "EmployeeCode": "MFS00307",
    "FullName": "Nguyễn Văn Luân",
    "Gender": "Nam",
    "DOB": "1989-05-12",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. HẠ TẦNG - VIỄN THÔNG",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0356057420",
    "Email": "luannv@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên quản lý điều hành DV VHKT&UCTT và phát triển DV HTVT mới"
  },
  {
    "MemberID": "mem_mfs_43",
    "EmployeeCode": "MFS00247",
    "FullName": "Nguyễn Văn Hường",
    "Gender": "Nam",
    "DOB": "1982-08-09",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. HẠ TẦNG - VIỄN THÔNG",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0904789866",
    "Email": "huongnv@mobifoneservice.com.vn",
    "UnionPosition": "UV UBKT Công đoàn Công ty",
    "Title": "Chuyên viên quản lý điều hành dịch vụ BTS cho thuê và phát triển DV HTVT mới"
  },
  {
    "MemberID": "mem_mfs_44",
    "EmployeeCode": "MFS00378",
    "FullName": "Vũ Huy Hoàng",
    "Gender": "Nam",
    "DOB": "1995-10-09",
    "Branch": 'Văn phòng Công ty MFS',
    "Department": "P. HẠ TẦNG - VIỄN THÔNG",
    "JoinDate": "2015-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0983370295",
    "Email": "hoangvh@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Chuyên viên quản lý điều hành và phát triển DV HTVT mới"
  },
  {
    "MemberID": "mem_1",
    "EmployeeCode": "MFS001",
    "FullName": "Hồ Thị Thu Phương",
    "Gender": "Nữ",
    "DOB": "1993-08-22",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Inbound",
    "JoinDate": "2025-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0772575711",
    "Email": "thuphuong11k@gmail.com",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV trực tiếp"
  },
  {
    "MemberID": "mem_2",
    "EmployeeCode": "MFS002",
    "FullName": "Định Thị Phượng",
    "Gender": "Nữ",
    "DOB": "1992-10-14",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Inbound",
    "JoinDate": "2025-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0903533140",
    "Email": "dinhphuong.92dn@gmail.com",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV trực tiếp"
  },
  {
    "MemberID": "mem_3",
    "EmployeeCode": "MFS003",
    "FullName": "Hà Thị Tịnh",
    "Gender": "Nữ",
    "DOB": "1984-09-09",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Inbound",
    "JoinDate": "2025-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0799403641",
    "Email": "hathitinh8409@gmail.com",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV trực tiếp"
  },
  {
    "MemberID": "mem_4",
    "EmployeeCode": "MFS004",
    "FullName": "Huỳnh Thị Khánh",
    "Gender": "Nữ",
    "DOB": "1992-12-29",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Inbound",
    "JoinDate": "2025-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0705980648",
    "Email": "khanhhuynh2912@gmail.com",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV trực tiếp"
  },
  {
    "MemberID": "mem_5",
    "EmployeeCode": "MFS005",
    "FullName": "Hà Thị Thanh Hiền",
    "Gender": "Nữ",
    "DOB": "1982-09-07",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Inbound",
    "JoinDate": "2025-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0828282662",
    "Email": "hathithanhhien2013@gmail.com",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV trực tiếp"
  },
  {
    "MemberID": "mem_6",
    "EmployeeCode": "MFS006",
    "FullName": "Nguyễn Thị Huyền Ngân",
    "Gender": "Nữ",
    "DOB": "1985-05-27",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Inbound",
    "JoinDate": "2025-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0901163616",
    "Email": "ngan0901163616@gmail.com",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV trực tiếp"
  },
  {
    "MemberID": "mem_7",
    "EmployeeCode": "MFS007",
    "FullName": "Trần Văn Tuấn",
    "Gender": "Nam",
    "DOB": "1996-11-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Bình Định",
    "JoinDate": "2024-12-01",
    "Status": "Đang hoạt động",
    "Phone": "0975109908",
    "Email": "tranvantuanmfs007@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành (cáp quang)"
  },
  {
    "MemberID": "mem_8",
    "EmployeeCode": "MFS008",
    "FullName": "Trần Vũ Hải",
    "Gender": "Nam",
    "DOB": "2000-03-03",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2024-11-01",
    "Status": "Đang hoạt động",
    "Phone": "0793619622",
    "Email": "tranvuhaimfs008@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên VHKT mạng truyền dẫn"
  },
  {
    "MemberID": "mem_9",
    "EmployeeCode": "MFS009",
    "FullName": "Mai Tiết Cương",
    "Gender": "Nam",
    "DOB": "1983-06-06",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2024-11-01",
    "Status": "Đang hoạt động",
    "Phone": "0905499509",
    "Email": "maitietcuongmfs009@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên chất lượng mạng truyền dẫn (trình độ kỹ thuật viên)"
  },
  {
    "MemberID": "mem_10",
    "EmployeeCode": "MFS010",
    "FullName": "Lê Phước Thịnh",
    "Gender": "Nam",
    "DOB": "1981-07-14",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2024-11-01",
    "Status": "Đang hoạt động",
    "Phone": "0326112233",
    "Email": "lephuocthinhmfs010@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hạ tầng truyền dẫn (trình độ kỹ thuật viên)"
  },
  {
    "MemberID": "mem_11",
    "EmployeeCode": "MFS011",
    "FullName": "Nguyễn Nho Quốc Khánh",
    "Gender": "Nam",
    "DOB": "1994-08-05",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2024-11-01",
    "Status": "Đang hoạt động",
    "Phone": "0765880445",
    "Email": "nguyennhoquockhanhmfs011@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hạ tầng truyền dẫn (trình độ kỹ thuật viên)"
  },
  {
    "MemberID": "mem_12",
    "EmployeeCode": "MFS012",
    "FullName": "Hoàng Thị Phương",
    "Gender": "Nam",
    "DOB": "1992-06-08",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2024-11-01",
    "Status": "Đang hoạt động",
    "Phone": "0971946234",
    "Email": "hoangthiphuongmfs012@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên chất lượng mạng truyền dẫn (trình độ kỹ sư)"
  },
  {
    "MemberID": "mem_13",
    "EmployeeCode": "MFS013",
    "FullName": "Thái Thị Mỹ Lộc",
    "Gender": "Nữ",
    "DOB": "1994-04-29",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Kon Tum",
    "JoinDate": "2024-11-21",
    "Status": "Đang hoạt động",
    "Phone": "0352993294",
    "Email": "thaithimylocmfs013@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_14",
    "EmployeeCode": "MFS014",
    "FullName": "Nguyễn Thị Tuyết Mai",
    "Gender": "Nữ",
    "DOB": "1996-09-06",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Kon Tum",
    "JoinDate": "2024-11-21",
    "Status": "Đang hoạt động",
    "Phone": "0842460996",
    "Email": "nguyenthituyetmaimfs014@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_15",
    "EmployeeCode": "MFS015",
    "FullName": "Nguyễn Như Thảo",
    "Gender": "Nữ",
    "DOB": "1997-08-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Kon Tum",
    "JoinDate": "2024-11-21",
    "Status": "Đang hoạt động",
    "Phone": "0948467097",
    "Email": "nguyennhuthaomfs015@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên đón tiếp khách hàng Cửa Hàng SIS"
  },
  {
    "MemberID": "mem_16",
    "EmployeeCode": "MFS016",
    "FullName": "Nguyễn Hoàng Trúc Hạ",
    "Gender": "Nữ",
    "DOB": "1984-05-31",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Inbound",
    "JoinDate": "2025-02-08",
    "Status": "Đang hoạt động",
    "Phone": "0935575631",
    "Email": "nguyenhoangtruchamfs016@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV trực tiếp"
  },
  {
    "MemberID": "mem_17",
    "EmployeeCode": "MFS017",
    "FullName": "Đặng Nam Trường Chinh",
    "Gender": "Nam",
    "DOB": "1989-08-19",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Bình Định",
    "JoinDate": "2025-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0985030449",
    "Email": "dangnamtruongchinhmfs017@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành (cáp quang)"
  },
  {
    "MemberID": "mem_18",
    "EmployeeCode": "MFS018",
    "FullName": "Trịnh Trung Thạo",
    "Gender": "Nam",
    "DOB": "1989-10-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Bình Định",
    "JoinDate": "2025-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0989432179",
    "Email": "trinhtrungthaomfs018@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành (cáp quang)"
  },
  {
    "MemberID": "mem_19",
    "EmployeeCode": "MFS019",
    "FullName": "Nguyễn Minh Quân",
    "Gender": "Nam",
    "DOB": "2002-01-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Văn phòng Công ty 7",
    "JoinDate": "2025-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0934935848",
    "Email": "nguyenminhquanmfs019@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_20",
    "EmployeeCode": "MFS020",
    "FullName": "Vũ Duy Hưng",
    "Gender": "Nam",
    "DOB": "2001-02-25",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-03-03",
    "Status": "Đang hoạt động",
    "Phone": "0778682538",
    "Email": "vuduyhungmfs020@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên chất lượng mạng truyền dẫn (trình độ kỹ sư)"
  },
  {
    "MemberID": "mem_21",
    "EmployeeCode": "MFS021",
    "FullName": "Nguyễn Phương Duyên",
    "Gender": "Nữ",
    "DOB": "1994-10-13",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Mạng lưới Miền Trung",
    "JoinDate": "2025-03-03",
    "Status": "Đang hoạt động",
    "Phone": "0905807760",
    "Email": "nguyenphuongduyenmfs021@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_22",
    "EmployeeCode": "MFS022",
    "FullName": "Trần Thị Hồng Lợi",
    "Gender": "Nữ",
    "DOB": "1998-06-28",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Kon Tum",
    "JoinDate": "2023-03-13",
    "Status": "Đang hoạt động",
    "Phone": "0937006249",
    "Email": "tranthihongloimfs022@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_23",
    "EmployeeCode": "MFS023",
    "FullName": "Nguyễn Thị Điệp",
    "Gender": "Nữ",
    "DOB": "2003-01-27",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Kon Tum",
    "JoinDate": "2023-03-13",
    "Status": "Đang hoạt động",
    "Phone": "0773408226",
    "Email": "nguyenthidiepmfs023@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên đón tiếp khách hàng Cửa Hàng SIS"
  },
  {
    "MemberID": "mem_24",
    "EmployeeCode": "MFS024",
    "FullName": "Đặng Văn Ngọc",
    "Gender": "Nam",
    "DOB": "1990-10-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2025-03-13",
    "Status": "Đang hoạt động",
    "Phone": "0905615007",
    "Email": "dangvanngocmfs024@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_25",
    "EmployeeCode": "MFS025",
    "FullName": "Trương Thị Như Uyên",
    "Gender": "Nữ",
    "DOB": "1992-08-24",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Đắk Nông",
    "JoinDate": "2025-03-10",
    "Status": "Đang hoạt động",
    "Phone": "0947920123",
    "Email": "truongthinhuuyenmfs025@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_26",
    "EmployeeCode": "MFS026",
    "FullName": "Lâm Diệu Hồng",
    "Gender": "Nữ",
    "DOB": "1992-08-23",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Phú Yên",
    "JoinDate": "2025-03-01",
    "Status": "Đang hoạt động",
    "Phone": "0934188890",
    "Email": "lamdieuhongmfs026@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_27",
    "EmployeeCode": "MFS027",
    "FullName": "Trần Thị Kim Liên",
    "Gender": "Nữ",
    "DOB": "1995-08-09",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Văn phòng Công ty 7",
    "JoinDate": "2025-04-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "tranthikimlienmfs027@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_28",
    "EmployeeCode": "MFS028",
    "FullName": "Lương Thị Thảo Vy",
    "Gender": "Nữ",
    "DOB": "2004-10-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Đắk Lắk",
    "JoinDate": "2025-04-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "luongthithaovymfs028@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_29",
    "EmployeeCode": "MFS029",
    "FullName": "Hoàng Thị Mỹ Dung",
    "Gender": "Nữ",
    "DOB": "1994-07-07",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Inbound",
    "JoinDate": "2025-03-20",
    "Status": "Đang hoạt động",
    "Phone": "0703603084",
    "Email": "hoangthimydungmfs029@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV trực tiếp"
  },
  {
    "MemberID": "mem_30",
    "EmployeeCode": "MFS030",
    "FullName": "Trần Trung Đức",
    "Gender": "Nam",
    "DOB": "1999-04-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Văn phòng Công ty 7",
    "JoinDate": "2025-05-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "trantrungducmfs030@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_31",
    "EmployeeCode": "MFS031",
    "FullName": "Nguyễn Thị Khánh Huyền",
    "Gender": "Nữ",
    "DOB": "2000-10-14",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Đắk Lắk",
    "JoinDate": "2025-05-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "nguyenthikhanhhuyenmfs031@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_32",
    "EmployeeCode": "MFS032",
    "FullName": "Lương Thị Thúy Liễu",
    "Gender": "Nữ",
    "DOB": "1989-11-20",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Phú Yên",
    "JoinDate": "2025-05-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "luongthithuylieumfs032@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_33",
    "EmployeeCode": "MFS033",
    "FullName": "Nguyễn Văn Minh Hào",
    "Gender": "Nam",
    "DOB": "2002-08-05",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-05-01",
    "Status": "Đang hoạt động",
    "Phone": "0935819092",
    "Email": "nguyenvanminhhaomfs033@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành, quản lý mạng truyền dẫn"
  },
  {
    "MemberID": "mem_34",
    "EmployeeCode": "MFS034",
    "FullName": "Bùi Thị Ánh Hoàng",
    "Gender": "Nữ",
    "DOB": "1985-09-25",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Callout & Xác minh thông tin",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0905696900",
    "Email": "buithianhhoangmfs034@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV callout"
  },
  {
    "MemberID": "mem_35",
    "EmployeeCode": "MFS035",
    "FullName": "Trần Lê Ngọc Anh",
    "Gender": "Nữ",
    "DOB": "1985-08-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Callout & Xác minh thông tin",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901124456",
    "Email": "tranlengocanhmfs035@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV callout"
  },
  {
    "MemberID": "mem_36",
    "EmployeeCode": "MFS036",
    "FullName": "Cao Xuân Dương",
    "Gender": "Nam",
    "DOB": "1994-07-28",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Quảng Trị",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0962635604",
    "Email": "caoxuanduongmfs036@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_37",
    "EmployeeCode": "MFS037",
    "FullName": "Phan Văn Cường",
    "Gender": "Nam",
    "DOB": "1992-09-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Quảng Trị",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0931419528",
    "Email": "phanvancuongmfs037@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành (cáp quang)"
  },
  {
    "MemberID": "mem_38",
    "EmployeeCode": "MFS038",
    "FullName": "Võ Minh Đạo",
    "Gender": "Nam",
    "DOB": "1995-12-10",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Bình Định",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0389282305",
    "Email": "vominhdaomfs038@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành (cáp quang)"
  },
  {
    "MemberID": "mem_39",
    "EmployeeCode": "MFS039",
    "FullName": "Phan Thanh Phương Thảo",
    "Gender": "Nữ",
    "DOB": "2002-11-24",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Văn phòng Công ty 7",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0935357464",
    "Email": "phanthanhphuongthaomfs039@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_40",
    "EmployeeCode": "MFS040",
    "FullName": "Trần Nhật Phương Thảo",
    "Gender": "Nữ",
    "DOB": "2000-11-12",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0773860312",
    "Email": "trannhatphuongthaomfs040@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_41",
    "EmployeeCode": "MFS041",
    "FullName": "Nguyễn Toàn Thắng",
    "Gender": "Nam",
    "DOB": "1984-05-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0903540688",
    "Email": "nguyentoanthangmfs041@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_42",
    "EmployeeCode": "MFS042",
    "FullName": "Nguyễn Văn Tân",
    "Gender": "Nam",
    "DOB": "1998-05-23",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0929085232",
    "Email": "nguyenvantanmfs042@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_43",
    "EmployeeCode": "MFS043",
    "FullName": "Nguyễn Văn Hưng",
    "Gender": "Nam",
    "DOB": "1991-02-08",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0905578961",
    "Email": "nguyenvanhungmfs043@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_44",
    "EmployeeCode": "MFS044",
    "FullName": "Phan Thành Phát",
    "Gender": "Nam",
    "DOB": "1993-01-03",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0703321146",
    "Email": "phanthanhphatmfs044@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_45",
    "EmployeeCode": "MFS045",
    "FullName": "Lê Văn Anh Pha",
    "Gender": "Nam",
    "DOB": "1994-07-13",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0905130794",
    "Email": "levananhphamfs045@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_46",
    "EmployeeCode": "MFS046",
    "FullName": "Nguyễn Hữu Anh Đức",
    "Gender": "Nam",
    "DOB": "1995-06-26",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0935880033",
    "Email": "nguyenhuuanhducmfs046@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_47",
    "EmployeeCode": "MFS047",
    "FullName": "Tào Quang Hưng",
    "Gender": "Nam",
    "DOB": "1992-03-27",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0939540777",
    "Email": "taoquanghungmfs047@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_48",
    "EmployeeCode": "MFS048",
    "FullName": "Lê Văn Tú",
    "Gender": "Nam",
    "DOB": "1994-10-30",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0394395217",
    "Email": "levantumfs048@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_49",
    "EmployeeCode": "MFS049",
    "FullName": "Nguyễn Dũng",
    "Gender": "Nam",
    "DOB": "1969-12-25",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "nguyendungmfs049@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_50",
    "EmployeeCode": "MFS050",
    "FullName": "Lê Hoài Bảo",
    "Gender": "Nam",
    "DOB": "1989-10-31",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "lehoaibaomfs050@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_51",
    "EmployeeCode": "MFS051",
    "FullName": "Hồ Văn Nhân",
    "Gender": "Nam",
    "DOB": "1976-12-18",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "hovannhanmfs051@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_52",
    "EmployeeCode": "MFS052",
    "FullName": "Nguyễn Anh Lân",
    "Gender": "Nam",
    "DOB": "1971-09-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "nguyenanhlanmfs052@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_53",
    "EmployeeCode": "MFS053",
    "FullName": "Nguyễn Quốc Khiêm",
    "Gender": "Nam",
    "DOB": "1979-08-18",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "nguyenquockhiemmfs053@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_54",
    "EmployeeCode": "MFS054",
    "FullName": "Hoàng Tiến Phong",
    "Gender": "Nam",
    "DOB": "1979-11-22",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "hoangtienphongmfs054@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_55",
    "EmployeeCode": "MFS055",
    "FullName": "Lê Lâm",
    "Gender": "Nam",
    "DOB": "1988-01-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "lelammfs055@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_56",
    "EmployeeCode": "MFS056",
    "FullName": "Lê Thanh Châu",
    "Gender": "Nam",
    "DOB": "1986-12-08",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "lethanhchaumfs056@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_57",
    "EmployeeCode": "MFS057",
    "FullName": "Phạm Ngọc Ánh",
    "Gender": "Nam",
    "DOB": "1988-10-13",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "phamngocanhmfs057@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_58",
    "EmployeeCode": "MFS058",
    "FullName": "Mai Tuấn Anh",
    "Gender": "Nam",
    "DOB": "1985-07-29",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "maituananhmfs058@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_59",
    "EmployeeCode": "MFS059",
    "FullName": "Nguyễn Đức Luyến",
    "Gender": "Nam",
    "DOB": "1994-10-06",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "nguyenducluyenmfs059@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_60",
    "EmployeeCode": "MFS060",
    "FullName": "Lê Phan Đăng Khoa",
    "Gender": "Nam",
    "DOB": "1979-09-12",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "lephandangkhoamfs060@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_61",
    "EmployeeCode": "MFS061",
    "FullName": "Trần Quốc Tâm",
    "Gender": "Nam",
    "DOB": "1986-08-25",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "tranquoctammfs061@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_62",
    "EmployeeCode": "MFS062",
    "FullName": "Trần Tiến Dũng",
    "Gender": "Nam",
    "DOB": "1973-04-20",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "trantiendungmfs062@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_63",
    "EmployeeCode": "MFS063",
    "FullName": "Nguyễn Trung Dũng",
    "Gender": "Nam",
    "DOB": "1975-07-28",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "nguyentrungdungmfs063@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_64",
    "EmployeeCode": "MFS064",
    "FullName": "Đoàn Văn Cường",
    "Gender": "Nam",
    "DOB": "1978-08-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "doanvancuongmfs064@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_65",
    "EmployeeCode": "MFS065",
    "FullName": "Nguyễn Hoàng Vũ",
    "Gender": "Nam",
    "DOB": "1983-11-30",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "nguyenhoangvumfs065@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_66",
    "EmployeeCode": "MFS066",
    "FullName": "Lê Trung Tùng",
    "Gender": "Nam",
    "DOB": "1989-10-08",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "letrungtungmfs066@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_67",
    "EmployeeCode": "MFS067",
    "FullName": "Đặng Phước Lý",
    "Gender": "Nam",
    "DOB": "1987-02-20",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "dangphuoclymfs067@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_68",
    "EmployeeCode": "MFS068",
    "FullName": "Đặng Văn Bình",
    "Gender": "Nam",
    "DOB": "1976-03-12",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "dangvanbinhmfs068@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_69",
    "EmployeeCode": "MFS069",
    "FullName": "Đặng Phước Diệu",
    "Gender": "Nam",
    "DOB": "1992-12-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "dangphuocdieumfs069@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_70",
    "EmployeeCode": "MFS070",
    "FullName": "Đặng Phước Quảng",
    "Gender": "Nam",
    "DOB": "1981-01-10",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "dangphuocquangmfs070@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_71",
    "EmployeeCode": "MFS071",
    "FullName": "Trương Cao Cường",
    "Gender": "Nam",
    "DOB": "1976-10-10",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "truongcaocuongmfs071@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_72",
    "EmployeeCode": "MFS072",
    "FullName": "Võ Thiện Nhã",
    "Gender": "Nam",
    "DOB": "1999-05-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "vothiennhamfs072@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_73",
    "EmployeeCode": "MFS073",
    "FullName": "Phan Ngọc Long",
    "Gender": "Nam",
    "DOB": "1980-07-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "phanngoclongmfs073@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_74",
    "EmployeeCode": "MFS074",
    "FullName": "Nguyễn Đại Hưng",
    "Gender": "Nam",
    "DOB": "1978-04-03",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "nguyendaihungmfs074@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_75",
    "EmployeeCode": "MFS075",
    "FullName": "Ngô Minh Hà",
    "Gender": "Nam",
    "DOB": "1975-10-25",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "ngominhhamfs075@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_76",
    "EmployeeCode": "MFS076",
    "FullName": "Nguyễn Văn Thi",
    "Gender": "Nam",
    "DOB": "1986-06-12",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "nguyenvanthimfs076@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_77",
    "EmployeeCode": "MFS077",
    "FullName": "Huỳnh Phước Hưng",
    "Gender": "Nam",
    "DOB": "1983-06-04",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "huynhphuochungmfs077@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_78",
    "EmployeeCode": "MFS078",
    "FullName": "Lưu Văn Tam",
    "Gender": "Nam",
    "DOB": "1985-01-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "luuvantammfs078@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_79",
    "EmployeeCode": "MFS079",
    "FullName": "Kiều Xuân Phi",
    "Gender": "Nam",
    "DOB": "1987-09-18",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-06-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "kieuxuanphimfs079@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe"
  },
  {
    "MemberID": "mem_80",
    "EmployeeCode": "MFS080",
    "FullName": "Nguyễn Thu Thủy",
    "Gender": "Nữ",
    "DOB": "1996-11-19",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Callout & Xác minh thông tin",
    "JoinDate": "2025-07-01",
    "Status": "Đang hoạt động",
    "Phone": "0847283738",
    "Email": "nguyenthuthuymfs080@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV callout"
  },
  {
    "MemberID": "mem_81",
    "EmployeeCode": "MFS081",
    "FullName": "Huỳnh Thị Hải Ly",
    "Gender": "Nữ",
    "DOB": "1984-11-12",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Callout & Xác minh thông tin",
    "JoinDate": "2025-07-07",
    "Status": "Đang hoạt động",
    "Phone": "0905488255",
    "Email": "huynhthihailymfs081@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV callout"
  },
  {
    "MemberID": "mem_82",
    "EmployeeCode": "MFS082",
    "FullName": "Võ Thị Thu Sương",
    "Gender": "Nữ",
    "DOB": "1997-12-22",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Callout & Xác minh thông tin",
    "JoinDate": "2025-07-07",
    "Status": "Đang hoạt động",
    "Phone": "0764076506",
    "Email": "vothithusuongmfs082@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV callout"
  },
  {
    "MemberID": "mem_83",
    "EmployeeCode": "MFS083",
    "FullName": "Dụng Thị Mỹ Tiên",
    "Gender": "Nữ",
    "DOB": "1983-09-11",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Callout & Xác minh thông tin",
    "JoinDate": "2025-07-09",
    "Status": "Đang hoạt động",
    "Phone": "0905704824",
    "Email": "dungthimytienmfs083@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV callout"
  },
  {
    "MemberID": "mem_84",
    "EmployeeCode": "MFS084",
    "FullName": "Lê Thanh Hưng",
    "Gender": "Nam",
    "DOB": "1981-03-26",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Quảng Trị",
    "JoinDate": "2025-07-01",
    "Status": "Đang hoạt động",
    "Phone": "0846020490",
    "Email": "lethanhhungmfs084@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành (cáp quang)"
  },
  {
    "MemberID": "mem_85",
    "EmployeeCode": "MFS085",
    "FullName": "Nguyễn Hữu Bích",
    "Gender": "Nam",
    "DOB": "1996-11-21",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Khánh Hòa",
    "JoinDate": "2025-07-01",
    "Status": "Đang hoạt động",
    "Phone": "0772426342",
    "Email": "nguyenhuubichmfs085@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_86",
    "EmployeeCode": "MFS086",
    "FullName": "Nguyễn Anh Đức",
    "Gender": "Nam",
    "DOB": "2001-04-20",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Bình Định",
    "JoinDate": "2025-07-01",
    "Status": "Đang hoạt động",
    "Phone": "0334937791",
    "Email": "nguyenanhducmfs086@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_87",
    "EmployeeCode": "MFS087",
    "FullName": "Lê Hữu Thịnh",
    "Gender": "Nam",
    "DOB": "2001-10-07",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Bình Định",
    "JoinDate": "2025-07-01",
    "Status": "Đang hoạt động",
    "Phone": "0395617946",
    "Email": "lehuuthinhmfs087@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_88",
    "EmployeeCode": "MFS088",
    "FullName": "Trần Đoan Kim",
    "Gender": "Nữ",
    "DOB": "2000-07-28",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Mạng lưới Miền Trung",
    "JoinDate": "2025-07-07",
    "Status": "Đang hoạt động",
    "Phone": "0774038869",
    "Email": "trandoankimmfs088@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_89",
    "EmployeeCode": "MFS089",
    "FullName": "Nguyễn Tiến Trung",
    "Gender": "Nam",
    "DOB": "1989-09-29",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-07-15",
    "Status": "Đang hoạt động",
    "Phone": "0905904581",
    "Email": "nguyentientrungmfs089@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_90",
    "EmployeeCode": "MFS090",
    "FullName": "Châu Thị Bích Luy",
    "Gender": "Nữ",
    "DOB": "1999-05-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Callout & Xác minh thông tin",
    "JoinDate": "2025-08-01",
    "Status": "Đang hoạt động",
    "Phone": "0949515444",
    "Email": "chauthibichluymfs090@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV callout"
  },
  {
    "MemberID": "mem_91",
    "EmployeeCode": "MFS091",
    "FullName": "Võ Thị Ánh Thủy",
    "Gender": "Nữ",
    "DOB": "1994-07-07",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Callout & Xác minh thông tin",
    "JoinDate": "2025-08-01",
    "Status": "Đang hoạt động",
    "Phone": "0706223528",
    "Email": "vothianhthuymfs091@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV callout"
  },
  {
    "MemberID": "mem_92",
    "EmployeeCode": "MFS092",
    "FullName": "Nguyễn Bảo Hoàng",
    "Gender": "Nam",
    "DOB": "1988-08-22",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Khánh Hòa",
    "JoinDate": "2025-08-01",
    "Status": "Đang hoạt động",
    "Phone": "0905887196",
    "Email": "nguyenbaohoangmfs092@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_93",
    "EmployeeCode": "MFS093",
    "FullName": "Nguyễn Ngọc Hoàng",
    "Gender": "Nam",
    "DOB": "1994-04-11",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Khánh Hòa",
    "JoinDate": "2025-08-01",
    "Status": "Đang hoạt động",
    "Phone": "0972107657",
    "Email": "nguyenngochoangmfs093@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_94",
    "EmployeeCode": "MFS094",
    "FullName": "Hồ Phương",
    "Gender": "Nam",
    "DOB": "2001-01-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-08-14",
    "Status": "Đang hoạt động",
    "Phone": "0908629582",
    "Email": "hophuongmfs094@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên chất lượng mạng truyền dẫn (trình độ kỹ sư)"
  },
  {
    "MemberID": "mem_95",
    "EmployeeCode": "MFS095",
    "FullName": "Đoàn Hiếu Kiên",
    "Gender": "Nam",
    "DOB": "2006-01-21",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Khánh Hòa",
    "JoinDate": "2025-09-01",
    "Status": "Đang hoạt động",
    "Phone": "0935988667",
    "Email": "doanhieukienmfs095@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_96",
    "EmployeeCode": "MFS096",
    "FullName": "Nguyễn Hồ Thương",
    "Gender": "Nam",
    "DOB": "1993-04-18",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Bình Định",
    "JoinDate": "2025-09-01",
    "Status": "Đang hoạt động",
    "Phone": "0774743265",
    "Email": "nguyenhothuongmfs096@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_97",
    "EmployeeCode": "MFS097",
    "FullName": "Nguyễn Thị Ánh Ngân",
    "Gender": "Nữ",
    "DOB": "2003-10-18",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Kon Tum",
    "JoinDate": "2025-09-01",
    "Status": "Đang hoạt động",
    "Phone": "0941822467",
    "Email": "nguyenthianhnganmfs097@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_98",
    "EmployeeCode": "MFS098",
    "FullName": "Phạm Ngọc Tấn",
    "Gender": "Nam",
    "DOB": "1984-12-16",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Quảng Ngãi",
    "JoinDate": "2025-10-01",
    "Status": "Đang hoạt động",
    "Phone": "0908002925",
    "Email": "phamngoctanmfs098@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_99",
    "EmployeeCode": "MFS099",
    "FullName": "Trần Như Phương",
    "Gender": "Nam",
    "DOB": "1979-12-30",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Quảng Ngãi",
    "JoinDate": "2025-10-01",
    "Status": "Đang hoạt động",
    "Phone": "0779464752",
    "Email": "trannhuphuongmfs099@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_100",
    "EmployeeCode": "MFS100",
    "FullName": "Trần Toán",
    "Gender": "Nam",
    "DOB": "1982-02-23",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Quảng Trị",
    "JoinDate": "2025-11-01",
    "Status": "Đang hoạt động",
    "Phone": "0943769444",
    "Email": "trantoanmfs100@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành (cáp quang)"
  },
  {
    "MemberID": "mem_101",
    "EmployeeCode": "MFS101",
    "FullName": "Phạm Văn Huy",
    "Gender": "Nam",
    "DOB": "1998-05-19",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Truyền dẫn - CLC - Đo kiểm - NOC",
    "JoinDate": "2025-10-28",
    "Status": "Đang hoạt động",
    "Phone": "0774700674",
    "Email": "phamvanhuymfs101@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên hỗ trợ quản lý, VHKT và ƯCTT"
  },
  {
    "MemberID": "mem_102",
    "EmployeeCode": "MFS102",
    "FullName": "Võ Hồ Phi Lực",
    "Gender": "Nam",
    "DOB": "1996-05-05",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "vohophilucmfs102@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_103",
    "EmployeeCode": "MFS103",
    "FullName": "Phạm Thị Vi",
    "Gender": "Nữ",
    "DOB": "1992-02-25",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "phamthivimfs103@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_104",
    "EmployeeCode": "MFS104",
    "FullName": "Nguyễn Ngà",
    "Gender": "Nam",
    "DOB": "1989-10-31",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Quảng Nam",
    "JoinDate": "2023-05-01",
    "Status": "Đang hoạt động",
    "Phone": "0901993499",
    "Email": "nguyenngaqnam89@gmail.com",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_105",
    "EmployeeCode": "MFS105",
    "FullName": "Nguyễn Anh Lân",
    "Gender": "Nam",
    "DOB": "1971-09-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Callout & Xác minh thông tin",
    "JoinDate": "2026-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0905750666",
    "Email": "lanna@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "NV lái xe"
  },
  {
    "MemberID": "mem_106",
    "EmployeeCode": "MFS106",
    "FullName": "Phan Sơn Hồng Thủy Tiên",
    "Gender": "Nữ",
    "DOB": "1990-01-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Inbound",
    "JoinDate": "2025-12-12",
    "Status": "Đang hoạt động",
    "Phone": "0949260090",
    "Email": "phansonhongthuytienmfs106@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "ĐTV trực tiếp"
  },
  {
    "MemberID": "mem_107",
    "EmployeeCode": "MFS107",
    "FullName": "Lê Phạm Ngọc Duy",
    "Gender": "Nam",
    "DOB": "1985-09-27",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Khánh Hòa",
    "JoinDate": "2026-03-01",
    "Status": "Đang hoạt động",
    "Phone": "0786378878/0976663579",
    "Email": "lephamngocduymfs107@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_108",
    "EmployeeCode": "MFS108",
    "FullName": "Triệu Văn Thiết",
    "Gender": "Nam",
    "DOB": "1990-12-27",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "UCTT Khánh Hòa",
    "JoinDate": "2026-03-01",
    "Status": "Đang hoạt động",
    "Phone": "0706057323",
    "Email": "trieuvanthietmfs108@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên vận hành"
  },
  {
    "MemberID": "mem_109",
    "EmployeeCode": "MFS109",
    "FullName": "Đặng Thị Khuyên",
    "Gender": "Nữ",
    "DOB": "1984-06-19",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2021-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0905817333",
    "Email": "dangthikhuyenmfs109@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_110",
    "EmployeeCode": "MFS110",
    "FullName": "Lê Thị Nương",
    "Gender": "Nữ",
    "DOB": "1984-09-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2021-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0905781567",
    "Email": "lethinuongmfs110@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên Tạp vụ"
  },
  {
    "MemberID": "mem_111",
    "EmployeeCode": "MFS111",
    "FullName": "Nguyễn Thị Yến",
    "Gender": "Nữ",
    "DOB": "1989-11-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2021-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0788537537",
    "Email": "nguyenthiyenmfs111@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_112",
    "EmployeeCode": "MFS112",
    "FullName": "Phan Thị Thu Hòa",
    "Gender": "Nữ",
    "DOB": "1988-07-08",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2021-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0932487666",
    "Email": "phanthithuhoamfs112@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_113",
    "EmployeeCode": "MFS113",
    "FullName": "Nguyễn Thị Tuyết Minh",
    "Gender": "Nữ",
    "DOB": "1983-04-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2021-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0935853536",
    "Email": "nguyenthituyetminhmfs113@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_114",
    "EmployeeCode": "MFS114",
    "FullName": "Phan Nguyễn Như Quỳnh",
    "Gender": "Nữ",
    "DOB": "1998-03-01",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2021-05-12",
    "Status": "Đang hoạt động",
    "Phone": "0799055355",
    "Email": "phannguyennhuquynhmfs114@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_115",
    "EmployeeCode": "MFS115",
    "FullName": "Đao Thị Mỹ Lý",
    "Gender": "Nữ",
    "DOB": "1987-03-22",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2023-09-17",
    "Status": "Đang hoạt động",
    "Phone": "0703653366",
    "Email": "daothimylymfs115@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_116",
    "EmployeeCode": "MFS116",
    "FullName": "Trần Khánh Linh",
    "Gender": "Nữ",
    "DOB": "1996-08-13",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2025-05-01",
    "Status": "Đang hoạt động",
    "Phone": "0988754997",
    "Email": "trankhanhlinhmfs116@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_117",
    "EmployeeCode": "MFS117",
    "FullName": "Lê Tùng Thắng",
    "Gender": "Nam",
    "DOB": "1991-02-15",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2021-05-01",
    "Status": "Đang hoạt động",
    "Phone": "0799134888",
    "Email": "letungthangmfs117@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_118",
    "EmployeeCode": "MFS118",
    "FullName": "Lê Thị Vũ Hằng",
    "Gender": "Nữ",
    "DOB": "1985-03-28",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0905965789",
    "Email": "lethivuhangmfs118@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_119",
    "EmployeeCode": "MFS119",
    "FullName": "Đoàn Ngọc Đình",
    "Gender": "Nam",
    "DOB": "1997-05-19",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0836579797",
    "Email": "doanngocdinhmfs119@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_120",
    "EmployeeCode": "MFS120",
    "FullName": "Nguyễn Viết Đạt",
    "Gender": "Nam",
    "DOB": "2001-08-16",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-03-01",
    "Status": "Đang hoạt động",
    "Phone": "0828287273",
    "Email": "nguyenvietdatmfs120@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_121",
    "EmployeeCode": "MFS121",
    "FullName": "Phan Thị Thanh",
    "Gender": "Nữ",
    "DOB": "1990-03-19",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-03-01",
    "Status": "Đang hoạt động",
    "Phone": "0931359369",
    "Email": "phanthithanhmfs121@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_122",
    "EmployeeCode": "MFS122",
    "FullName": "Lê Hoài Bảo",
    "Gender": "Nam",
    "DOB": "1989-10-31",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0901234567",
    "Email": "lehoaibaomfs122@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_123",
    "EmployeeCode": "MFS123",
    "FullName": "Nguyễn Dũng",
    "Gender": "Nam",
    "DOB": "1969-12-25",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0906425552",
    "Email": "nguyendungmfs123@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_124",
    "EmployeeCode": "MFS124",
    "FullName": "Nguyễn Thùy Trang",
    "Gender": "Nữ",
    "DOB": "1994-04-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0935397953",
    "Email": "nguyenthuytrangmfs124@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_125",
    "EmployeeCode": "MFS125",
    "FullName": "Trần Thị Phương Ly",
    "Gender": "Nữ",
    "DOB": "1977-10-09",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-03-06",
    "Status": "Đang hoạt động",
    "Phone": "0915123880",
    "Email": "tranthiphuonglymfs125@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên tạp vụ"
  },
  {
    "MemberID": "mem_126",
    "EmployeeCode": "MFS126",
    "FullName": "Lưu Bích Trâm",
    "Gender": "Nữ",
    "DOB": "1981-11-05",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0899373979",
    "Email": "luubichtrammfs126@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên tạp vụ"
  },
  {
    "MemberID": "mem_127",
    "EmployeeCode": "MFS127",
    "FullName": "Trần Thị Ngọc Diệp",
    "Gender": "Nữ",
    "DOB": "1996-09-28",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0384780121",
    "Email": "tranthingocdiepmfs127@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_128",
    "EmployeeCode": "MFS128",
    "FullName": "Võ Bích Vân",
    "Gender": "Nữ",
    "DOB": "1967-11-25",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0908570355",
    "Email": "vobichvanmfs128@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên tạp vụ"
  },
  {
    "MemberID": "mem_129",
    "EmployeeCode": "MFS129",
    "FullName": "Nguyễn Thị Kim Loan",
    "Gender": "Nữ",
    "DOB": "1981-05-20",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0793850444",
    "Email": "nguyenthikimloanmfs129@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_130",
    "EmployeeCode": "MFS130",
    "FullName": "Lê Thị Thu Hạnh",
    "Gender": "Nữ",
    "DOB": "2000-02-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0785812320",
    "Email": "lethithuhanhmfs130@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_131",
    "EmployeeCode": "MFS131",
    "FullName": "Chu Thị Dung",
    "Gender": "Nữ",
    "DOB": "1994-12-16",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0905061294",
    "Email": "chuthidungmfs131@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_132",
    "EmployeeCode": "MFS132",
    "FullName": "Nguyễn Thị Kim Tuyết",
    "Gender": "Nữ",
    "DOB": "1982-09-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-02-01",
    "Status": "Đang hoạt động",
    "Phone": "0931247779",
    "Email": "nguyenthikimtuyetmfs132@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_133",
    "EmployeeCode": "MFS133",
    "FullName": "Hoàng Thị Thu Hiền",
    "Gender": "Nữ",
    "DOB": "1987-11-04",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-03-01",
    "Status": "Đang hoạt động",
    "Phone": "0906438385",
    "Email": "hoangthithuhienmfs133@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  },
  {
    "MemberID": "mem_134",
    "EmployeeCode": "MFS134",
    "FullName": "Nguyễn Ngọc Hải",
    "Gender": "Nam",
    "DOB": "1970-09-02",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "HTNV Khánh Hòa",
    "JoinDate": "2026-03-01",
    "Status": "Đang hoạt động",
    "Phone": "0784001038",
    "Email": "nguyenngochaimfs134@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_135",
    "EmployeeCode": "MFS135",
    "FullName": "Nguyễn Hữu Thành",
    "Gender": "Nam",
    "DOB": "2004-09-12",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-01-01",
    "Status": "Đang hoạt động",
    "Phone": "0794144777",
    "Email": "nguyenhuuthanhmfs135@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên lái xe văn phòng"
  },
  {
    "MemberID": "mem_136",
    "EmployeeCode": "MFS136",
    "FullName": "Phan Quốc Hậu",
    "Gender": "Nam",
    "DOB": "2002-05-25",
    "Branch": "MFS Chi nhánh Miền Trung",
    "Department": "Khác",
    "JoinDate": "2026-01-15",
    "Status": "Đang hoạt động",
    "Phone": "0905310879",
    "Email": "phanquochaumfs136@mobifoneservice.com.vn",
    "UnionPosition": "Đoàn viên",
    "Title": "Nhân viên nhập liệu, tổng hợp và thống kê số liệu"
  }
]

export const INITIAL_NEWS: NewsPost[] = [
  {
    id: 'news_1',
    title: 'Khen thưởng tập thể, cá nhân có thành tích xuất sắc trong Chiến dịch Phát triển Số Q1.2026',
    content: `Ban chấp hành Công đoàn Công ty CP Dịch vụ Kỹ thuật Mobifone xin gửi thông báo biểu dương các chi đoàn cơ sở đã tích cực hoàn thành xuất sắc các chỉ tiêu công nghệ và kinh doanh trong Quý 1 năm 2026.\n\nChi đoàn cơ sở phòng Công nghệ số dẫn đầu với dự án phát triển các sản phẩm "Đại hội số" và hệ thống "Union Connect". Trưởng phòng Nguyễn Sông Hương cùng toàn thể thành viên phòng Công nghệ số được Công đoàn Công ty ghi danh khen thưởng, trao tặng kỷ niệm chương vì đóng góp đẩy mạnh Chuyển đổi số của tổ chức.\n\nChúc toàn thể đoàn viên giữ vững ngọn lửa nhiệt huyết, tiếp tục xung kích trong mọi hoạt động sản xuất kinh doanh!`,
    category: 'Thi đua - Khen thưởng',
    authorName: 'BCH Công đoàn Tổng',
    createdAt: '2026-05-28T08:30:00Z',
    likes: 24,
    likedBy: ['hungnv@mobifoneservice.com.vn', 'lamtt@mobifoneservice.com.vn'],
    attachments: [
      { name: 'Quyet_Dinh_Khen_Thuong_Q1_2026.pdf', size: '1.2 MB', url: '#' }
    ]
  },
  {
    id: 'news_2',
    title: 'Phát động giải chạy trực tuyến "MobifoneService Run 2026: Sải bước tiên phong - Kết nối số"',
    content: `Chào mừng các ngày lễ lớn trong năm và thúc đẩy tinh thần rèn luyện sức khỏe, BCH Công đoàn Công ty phối hợp cùng Phòng Công nghệ số phát động giải chạy bộ "MobifoneService Run 2026" dành cho toàn thể người lao động và đoàn viên trên khắp 4 chi nhánh toàn quốc.\n\nThời gian đăng ký: Từ nay đến hết ngày 05/06/2026.\nThời gian giải chạy: 10 ngày từ 06/06 đến 16/06/2026.\nTập hợp các chặng đường qua ứng dụng di động sẽ tự động cập nhật về bảng xếp hạng trực tiếp trên hệ thống Union Connect. Toàn bộ kinh phí bồi dưỡng vận động viên sẽ quy đổi tương ứng số Km hoàn thành để gửi tặng quỹ "Nâng bước em tới trường".`,
    category: 'Hoạt động phong trào',
    authorName: 'BCH Công đoàn Tổng',
    createdAt: '2026-05-25T14:15:00Z',
    likes: 42,
    likedBy: ['huongns@mobifoneservice.com.vn', 'nguyenhoangvy182@gmail.com', 'hungnv@mobifoneservice.com.vn'],
    externalLink: 'https://mobifoneservice.com.vn/hoat-dong-noi-bo',
    attachments: [
      { name: 'The_Le_Giai_Chay_Run_2026.pdf', size: '840 KB', url: '#' },
      { name: 'Huong_Dan_Ghi_Nhan_Ket_Qua.pdf', size: '1.5 MB', url: '#' }
    ]
  },
  {
    id: 'news_3',
    title: 'Kế hoạch học tập nghị quyết Công đoàn cấp trên và Chuyển đổi số doanh nghiệp 2026',
    content: `Thực hiện kế hoạch bồi dưỡng kiến thức cho Đoàn viên Thanh niên và Lao động trẻ, BCH Công đoàn cơ sở ra văn bản chỉ đạo tổ chức buổi sinh hoạt chuyên đề:\n\n1. Học tập nghị quyết của Tổng Liên đoàn Lao động Việt Nam về Đổi mới hoạt động công đoàn.\n2. Ứng dụng AI nâng cao hiệu suất lao động cá nhân - Do Trưởng phòng Nguyễn Sông Hương biên soạn và hướng dẫn.\n\nYêu cầu các Admin Chi nhánh lập danh sách đoàn viên tham gia trực tiếp và trực tuyến trước ngày 02/06/2026. Chương trình sẽ ghi nhận điểm thi đua cho từng chi nhánh cơ sở.`,
    category: 'Tin tức học tập',
    authorName: 'BCH Công đoàn Tổng',
    createdAt: '2026-05-20T09:00:00Z',
    likes: 15,
    likedBy: [],
    attachments: [
      { name: 'Tai_Lieu_Sinh_Hoat_Cong_Doan_AI.pdf', size: '3.4 MB', url: '#' }
    ]
  }
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'com_1',
    postId: 'news_1',
    authorName: 'Trần Tiến Lâm',
    authorRole: 'Đoàn viên MFS Hà Nội',
    authorAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    content: 'Chúc mừng phòng Công nghệ số đứng đầu thi đua toàn đoàn ạ! Rất tự hào được đóng góp một phần nhỏ bé.',
    createdAt: '2026-05-28T09:15:00Z'
  },
  {
    id: 'com_2',
    postId: 'news_1',
    authorName: 'Tô Thị Hồng Phước',
    authorRole: 'Admin MFS Miền Nam',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    content: 'Chúc mừng chị Nguyễn Sông Hương cùng toàn phòng! MFS Miền Nam sẽ bứt phá mạnh mẽ trong Quý 2 để cạnh tranh công bằng luôn nhé!',
    createdAt: '2026-05-28T10:30:00Z'
  },
  {
    id: 'com_3',
    postId: 'news_2',
    authorName: 'Nguyễn Hoàng Vy',
    authorRole: 'Đoàn viên MFS Miền Nam',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    content: 'Đã sẵn sàng giày chạy cho MobifoneService Run 2026! Vừa chạy khỏe vừa giúp đỡ các cháu nhỏ, giải đấu quá ý nghĩa luôn.',
    createdAt: '2026-05-25T15:00:00Z'
  }
];
